### ISSUE TITLE
how could I compute the POP when buy 1 Call at A and Sell 1 Call of higher strike B

### ISSUE THREAD

**Issue by jagernicolas** [rgaveiga/optionlab#4]
how could I compute the POP in the following case :

**Buy 1 Call at A and Sell 1 Call of higher strike B**

```
from optionlab.black_scholes import getBSinfo
from optionlab.support import getPoP

# Input parameters
stockprice = 22.97
strike_A = 19.0  # Lower strike (buy)
strike_B = 20.0  # Higher strike (sell)
interestrate = 4.26
dividendyield = 0.0
volatility_A = 52.61 # Implied volatility IV
volatility_B = 51.97 # Implied volatility IV
volatility = 90.79 # historic vol. for the year
days2maturity = 55 ## 2024 April 19

# Convert percentages to fractions and years
interestrate = interestrate / 100
dividendyield = dividendyield / 100
volatility = volatility / 100
volatility_A = volatility_A / 100
volatility_B = volatility_B / 100
time2maturity = days2maturity / 365

# Perform Black-Scholes calculations for option at strike A
callprice_A, _, _, _, _, _, _, _, _, _ = getBSinfo(
    stockprice,
    strike_A,
    interestrate,
    volatility_A,
    time2maturity,
    dividendyield
)

# Perform Black-Scholes calculations for option at strike B
callprice_B, _, _, _, _, _, _, _, _, _ = getBSinfo(
    stockprice,
    strike_B,
    interestrate,
    volatility_B,
    time2maturity,
    dividendyield
)

# Calculate strategy payoff
strategy_payoff = callprice_A - callprice_B

# Calculate breakeven point
breakeven = strike_A + strategy_payoff


# Compute the PoP using the same input data as in the previous example
pop=getPoP([[strike_A,strike_B]],"black-scholes",stockprice=stockprice,volatility=volatility,interestrate=interestrate,time2maturity=time2maturity,dividendyield=dividendyield)

# Output results
print("Call Option at Strike A:")
print("========================")
print("Strike Price: %.2f" % strike_A)
print("Option Price: %.2f" % callprice_A)
print("\n")
print("Call Option at Strike B:")
print("========================")
print("Strike Price: %.2f" % strike_B)
print("Option Price: %.2f" % callprice_B)
print("\n")
print("Strategy Payoff (Buy 1 Call at A, Sell 1 Call at B): %.2f" % strategy_payoff)
print("Breakeven Point: %.2f" % breakeven)
print("Probability of Profit (PoP) is %.2f%%" % (pop*100))
```

results:
```
Call Option at Strike A:
========================
Strike Price: 19.00
Option Price: 4.47


Call Option at Strike B:
========================
Strike Price: 20.00
Option Price: 3.69


Strategy Payoff (Buy 1 Call at A, Sell 1 Call at B): 0.78
Breakeven Point: 19.78
Probability of Profit (PoP) is 5.53%

```

first comment goes to the options prices. I was expecting to get the same from here:
https://www.barchart.com/stocks/quotes/PLTR/options?expiration=2024-04-19-m&view=sbs&moneyness=allRows

second the POP is quiet small, I was expecting something at 75%.

can you help me to understand what I do wrong ?

**Comment by rgaveiga** [comment]
In
pop=getPoP([[strike_A,strike_B]],"black-scholes",stockprice=stockprice,volatility=volatility,interestrate=interestrate,time2maturity=time2maturity,dividendyield=dividendyield)
the first argument to be provided is not a list with the strikes of the options, but a list containing the prices of the underlying asset that represent the boundaries within which the strategy is profitable.

**Comment by rgaveiga** [comment]
Regarding the prices of the options calculated from the implied volatilities that you provided, I used other Black-Scholes calculator that I found through random googling: https://www.mystockoptions.com/black-scholes.cfm?ticker=&s=22.97&x=20&t=0.151&r=4.26%25&v=51.97&calculate=Calculate I got the same as you with optionlab in both cases, with little differences due to rounding.

**Comment by jagernicolas** [comment]
I also do the B-S equation math in a spreadsheet and I found the same. So my guess is they are using at least one parameter with a different value  (volatility/interest rate come in my mind).

Still, I have no idea about how the POP has to be calculated. I still looking to learn about it.

**Comment by rgaveiga** [comment]
It is possible. To obtain the same results, it is mandatory to use the same parameters. Particularly the interest rate used in the calculations is often not shown, which prevents reproducibility.

**Comment by rgaveiga** [comment]
You can find how OptionLab calculates the PoP here: https://medium.com/@rgaveiga/probability-of-profit-of-an-options-strategy-from-the-black-scholes-model-6146585f0fa0
