### ISSUE TITLE
cannot import name 'pi' from 'scipy' 

### ISSUE THREAD

**Issue by pmirla** [rgaveiga/optionlab#9]
Have this seen this error? @rgaveiga 
(python_311) (.conda) (base) pavanmirla@Pavans-MacBook-M1 openbb % python --version
Python 3.11.8

ImportError: cannot import name 'pi' from 'scipy' (/opt/homebrew/lib/python3.11/site-packages/scipy/__init__.py)

I have MAC M1.

Thanks

**Comment by marc-at-brightnight** [comment]
This issue should be fixed as of v0.2.0
